"""initial migration

Revision ID: 16556aa12bfe
Revises: 
Create Date: 2022-03-18 01:53:33.069827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16556aa12bfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_index(op.f('ix_client_username'), 'client', ['username'], unique=False)
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanic_email'), 'mechanic', ['email'], unique=True)
    op.create_index(op.f('ix_mechanic_username'), 'mechanic', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanic_username'), table_name='mechanic')
    op.drop_index(op.f('ix_mechanic_email'), table_name='mechanic')
    op.drop_table('mechanic')
    op.drop_index(op.f('ix_client_username'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
